# Generated by Django 3.0.9 on 2020-08-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('articleNo', models.IntegerField(primary_key=True, serialize=False)),
                ('authorNo', models.IntegerField()),
                ('headline', models.CharField(max_length=20)),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='static/article_image')),
                ('article_type', models.CharField(blank=True, choices=[('爱宠故事', '爱宠故事'), ('科普知识', '科普知识'), ('交流讨论', '交流讨论')], max_length=10, null=True)),
                ('date', models.DateField(null=True)),
                ('views', models.IntegerField(default=0, null=True)),
                ('likes', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderNo', models.IntegerField()),
                ('receiverNo', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('text', models.TextField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/chat_img')),
                ('video', models.FileField(blank=True, null=True, upload_to='static/chat_media')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleNo', models.IntegerField(default=1)),
                ('time', models.DateField(null=True)),
                ('userNo', models.IntegerField(null=True)),
                ('text', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('keeperNo', models.IntegerField(primary_key=True, serialize=False)),
                ('realNo', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('女', '女'), ('男', '男')], max_length=2)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/keeper_photo')),
                ('intro', models.TextField(null=True)),
                ('ID_number', models.CharField(default='31022619991229526', max_length=18)),
                ('interview_time', models.CharField(blank=True, max_length=6, null=True)),
                ('pet_type', models.CharField(max_length=10)),
                ('star', models.FloatField(default=3)),
                ('city', models.CharField(default='上海', max_length=2)),
                ('district', models.CharField(choices=[('黄浦区', '黄浦区'), ('徐汇区', '徐汇区'), ('长宁区', '长宁区'), ('静安区', '静安区'), ('普陀区', '普陀区'), ('虹口区', '虹口区'), ('杨浦区', '杨浦区'), ('闵行区', '闵行区'), ('宝山区', '宝山区'), ('嘉定区', '嘉定区'), ('金山区', '金山区'), ('松江区', '松江区'), ('青浦区', '青浦区'), ('奉贤区', '奉贤区'), ('崇明区', '崇明区'), ('浦东新区', '浦东新区')], max_length=4)),
                ('start_time', models.DateField(blank=True, max_length=500, null=True)),
                ('end_time', models.DateField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNo', models.IntegerField(primary_key=True, serialize=False)),
                ('customerNo', models.IntegerField()),
                ('keeperNo', models.IntegerField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('money', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(choices=[('已完成', '已完成'), ('正在进行', '正在进行')], default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keeperNo', models.IntegerField()),
                ('service_type', models.CharField(choices=[('遛狗', '遛狗'), ('寄养', '寄养'), ('上门照看', '上门照看'), ('看房子', '看房子')], max_length=4)),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.IntegerField()),
                ('customerNo', models.IntegerField()),
                ('keeperNo', models.IntegerField()),
                ('score', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('co_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('No', models.IntegerField(primary_key=True, serialize=False)),
                ('ID', models.CharField(max_length=20, unique=True)),
                ('code', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/user_img')),
                ('keeper_if', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0)),
            ],
        ),
    ]
